### PR TITLE
WIP - Pre refacor

### PR DESCRIPTION
**Pull request by remmel**
The objective of that PR is to refactor the pre script in order to
- avoid duplicated code
- use pathlib as it makes the code more readable

Do you prefer to split that in multiple PR or having only one PR? If it not bother you, it might be better to have multiples (working) PRs to make it easily to validate on your side.

~~In that first commit, I only move part of the `helper3dg.py` which is only used in pre scripts. Do you confirm that that code is from you? (thus I do not need to add Inria licence header).~~

### CODE REVIEW

**Comment by lizhan17** [comment]
i prefer to have one PR. 

but keep inria's code at helper3dg.py (under thirdparty folder)

**Comment by remmel** [comment]
(removing my useless commit; after you comment, make that PR close automatically)

**Comment by lizhan17** [comment]
is this PR ready to merge ? or last PR

**Comment by remmel** [comment]
> is this PR ready to merge ? or last PR

Not yet, I'll let you know ("draft PR")

**Comment by lizhan17** [comment]
thank you, take your time, i am newbee to colab with github pr.

**Comment by remmel** [comment]
That PR can be merged:
- I did not modify `pre_technicolor.py` as I don't have the dataset (if you can test on you side, I can modify  `pre_technicolor.py` "blindly")
- in `script/pre_*`:
  - migrate to `pathlib`
  - remove some dead code (not everything, to simplify the merge/review)
  - introduce `write_colmap` function which deal to create the colmap db input and txt files (and avoid doing it in multiple places) (note that `pre_no_prior.py` has its own colmap db related code ; 
  - `extractframes` not duplicated anymore
  - use `.symlink_to` instead of `.copy`
 - to make sure everything is still working:
   - compare the database via https://sqlitebrowser.org/
   - `colmap gui --import_path sparse/0/ --database_path input.db --image_path images`
   - train on the related dataset and compare the result in the viewer
   - review my commits
   
In another PR, some more refactor can be make such as
- `extractframes` to `utils_pre.py`
- in `pre_immersive_[un]distorted.py`, factorize `imageundistort` / `imageundistort_no_mapper`
- use pathlib in `helper3dg.py`

**Comment by lizhan17** [comment]
# check that cx is almost w /2, idem for cy
assert abs(cx - w / 2) / cx < 0.10, f"cx is not close to w/2: {cx}, w: {w}"
assert abs(cy - h / 2) / cy < 0.10, f"cy is not close to h/2: {cy}, h: {h}"

Could we discard that part. As some images will have large shift from the camera centers. 

i need time to run and check the code (it is very busy for me now). As preprocessing scripts for immersive dataset are revised many times to achieve best results.

I really appreciate your contribution to the preprocessing part. The rest of the training code (released in last december) was already refactored from my internal original implementation for open-source purposes. I'm concerned that further changes to the code might introduce discrepancy of metrics and we don't have time to test it currently. Please make a fork of our code if you want to further change the rest part.

**Comment by remmel** [comment]
Hello,
I've commented the assertion. 10% is large shift (if w=100; cx=45.5 is still true; not sure if we can find that in commercial camera, but probably in cropped/resized/translated images). 

Are you more confortable if I make further checks by diff comparing the output folders (old vs new; but probably excluding colmap output as values changes every times) ?

**Comment by lizhan17** [comment]
if we can check the number of points are similar and the camera poses are exactly same, then i will merge. if you don't time, i can check in the serveral weeks. Thank you anyway.

especially for the immersive dataset, there are some randomness in the prescript.

**Comment by remmel** [comment]
Hello,

I double-checked `pre_n3d.py`, `pre_immersive_distorted.py` and `pre_immersive_undistorted.py` using https://github.com/remmel/colmap-diff/blob/main/diff.py from https://github.com/remmel/colmap-diff (read the bin, read the sqlite) and there are no difference (intrinsics, extrinsics/poses) :
- colmap_X/sparse/0/images.bin
- colmap_X/sparse/0/cameras.bin
- colmap_X/sparse/0/points3D.bin : less than 1% difference on the number of sparce point; which is expected
- colmap_X/manual/cameras.txt
- colmap_X/manual/images.txt
- colmap_X/input.db (table cameras and images)
- colmap_0/images/camera_0001.png (for immersive undist + dist)
- camera_0001.npy  (for immersive dist) 


<details>
  <summary>diff.py logs</summary>

```
/home/remmel/anaconda3/envs/spacetime/bin/python /home/remmel/workspace/colmap-diff/diff.py 
Checking /home/remmel/workspace/dataset/Neural3D/before/flame_steak/colmap_* with after
⚠️ colmap_0: space 3D points: 3861 vs 3843 - 0.47% difference
⚠️ colmap_1: space 3D points: 3907 vs 3924 - 0.44% difference
⚠️ colmap_10: space 3D points: 3927 vs 3921 - 0.15% difference
⚠️ colmap_11: space 3D points: 3873 vs 3876 - 0.08% difference
⚠️ colmap_12: space 3D points: 3929 vs 3921 - 0.20% difference
⚠️ colmap_13: space 3D points: 3905 vs 3912 - 0.18% difference
⚠️ colmap_14: space 3D points: 3971 vs 3965 - 0.15% difference
⚠️ colmap_15: space 3D points: 3837 vs 3823 - 0.36% difference
⚠️ colmap_16: space 3D points: 3854 vs 3853 - 0.03% difference
⚠️ colmap_17: space 3D points: 3830 vs 3822 - 0.21% difference
⚠️ colmap_18: space 3D points: 3877 vs 3868 - 0.23% difference
⚠️ colmap_19: space 3D points: 3858 vs 3851 - 0.18% difference
⚠️ colmap_2: space 3D points: 3885 vs 3895 - 0.26% difference
⚠️ colmap_20: space 3D points: 3831 vs 3817 - 0.37% difference
⚠️ colmap_21: space 3D points: 3901 vs 3894 - 0.18% difference
⚠️ colmap_22: space 3D points: 3867 vs 3866 - 0.03% difference
⚠️ colmap_23: space 3D points: 3889 vs 3885 - 0.10% difference
⚠️ colmap_24: space 3D points: 3945 vs 3944 - 0.03% difference
⚠️ colmap_25: space 3D points: 3935 vs 3940 - 0.13% difference
⚠️ colmap_26: space 3D points: 3894 vs 3886 - 0.21% difference
⚠️ colmap_27: space 3D points: 3858 vs 3860 - 0.05% difference
⚠️ colmap_28: space 3D points: 3951 vs 3954 - 0.08% difference
⚠️ colmap_29: space 3D points: 3896 vs 3898 - 0.05% difference
⚠️ colmap_3: space 3D points: 3883 vs 3874 - 0.23% difference
⚠️ colmap_30: space 3D points: 3965 vs 3962 - 0.08% difference
⚠️ colmap_31: space 3D points: 3938 vs 3935 - 0.08% difference
⚠️ colmap_32: space 3D points: 3869 vs 3864 - 0.13% difference
⚠️ colmap_33: space 3D points: 3960 vs 3951 - 0.23% difference
⚠️ colmap_34: space 3D points: 3889 vs 3886 - 0.08% difference
⚠️ colmap_35: space 3D points: 3895 vs 3896 - 0.03% difference
⚠️ colmap_36: space 3D points: 3932 vs 3943 - 0.28% difference
⚠️ colmap_37: space 3D points: 3927 vs 3926 - 0.03% difference
⚠️ colmap_38: space 3D points: 3956 vs 3942 - 0.35% difference
⚠️ colmap_39: space 3D points: 3959 vs 3971 - 0.30% difference
⚠️ colmap_4: space 3D points: 3922 vs 3913 - 0.23% difference
⚠️ colmap_40: space 3D points: 3920 vs 3903 - 0.43% difference
⚠️ colmap_41: space 3D points: 3967 vs 3987 - 0.50% difference
⚠️ colmap_42: space 3D points: 3972 vs 3963 - 0.23% difference
⚠️ colmap_43: space 3D points: 3952 vs 3967 - 0.38% difference
⚠️ colmap_45: space 3D points: 3913 vs 3931 - 0.46% difference
⚠️ colmap_46: space 3D points: 3930 vs 3919 - 0.28% difference
⚠️ colmap_47: space 3D points: 3967 vs 3966 - 0.03% difference
⚠️ colmap_48: space 3D points: 3974 vs 3979 - 0.13% difference
⚠️ colmap_49: space 3D points: 3957 vs 3948 - 0.23% difference
⚠️ colmap_5: space 3D points: 3910 vs 3906 - 0.10% difference
⚠️ colmap_6: space 3D points: 3991 vs 3993 - 0.05% difference
⚠️ colmap_7: space 3D points: 3811 vs 3826 - 0.39% difference
⚠️ colmap_8: space 3D points: 3889 vs 3883 - 0.15% difference
⚠️ colmap_9: space 3D points: 3872 vs 3876 - 0.10% difference
Checking /home/remmel/workspace/dataset/immersive/before/02_Flames_dist/colmap_* with after
⚠️ colmap_0: space 3D points: 1843 vs 1840 - 0.16% difference
⚠️ colmap_1: space 3D points: 1880 vs 1878 - 0.11% difference
⚠️ colmap_10: space 3D points: 2983 vs 2955 - 0.94% difference
⚠️ colmap_11: space 3D points: 2998 vs 2969 - 0.97% difference
⚠️ colmap_12: space 3D points: 3045 vs 3046 - 0.03% difference
⚠️ colmap_13: space 3D points: 2966 vs 2969 - 0.10% difference
⚠️ colmap_14: space 3D points: 2736 vs 2740 - 0.15% difference
⚠️ colmap_15: space 3D points: 2647 vs 2633 - 0.53% difference
⚠️ colmap_16: space 3D points: 2680 vs 2689 - 0.34% difference
⚠️ colmap_17: space 3D points: 2726 vs 2708 - 0.66% difference
⚠️ colmap_18: space 3D points: 2690 vs 2711 - 0.78% difference
⚠️ colmap_19: space 3D points: 2711 vs 2714 - 0.11% difference
⚠️ colmap_2: space 3D points: 2076 vs 2077 - 0.05% difference
⚠️ colmap_20: space 3D points: 2544 vs 2541 - 0.12% difference
⚠️ colmap_21: space 3D points: 2634 vs 2622 - 0.46% difference
⚠️ colmap_23: space 3D points: 2672 vs 2686 - 0.52% difference
⚠️ colmap_24: space 3D points: 2766 vs 2751 - 0.54% difference
⚠️ colmap_25: space 3D points: 2637 vs 2620 - 0.64% difference
⚠️ colmap_26: space 3D points: 2727 vs 2720 - 0.26% difference
⚠️ colmap_27: space 3D points: 2681 vs 2696 - 0.56% difference
⚠️ colmap_28: space 3D points: 2674 vs 2667 - 0.26% difference
⚠️ colmap_29: space 3D points: 2605 vs 2603 - 0.08% difference
⚠️ colmap_3: space 3D points: 2174 vs 2162 - 0.55% difference
⚠️ colmap_30: space 3D points: 2517 vs 2511 - 0.24% difference
⚠️ colmap_31: space 3D points: 2618 vs 2607 - 0.42% difference
⚠️ colmap_32: space 3D points: 2559 vs 2575 - 0.63% difference
⚠️ colmap_33: space 3D points: 2449 vs 2462 - 0.53% difference
⚠️ colmap_34: space 3D points: 2265 vs 2261 - 0.18% difference
⚠️ colmap_35: space 3D points: 2139 vs 2124 - 0.70% difference
⚠️ colmap_36: space 3D points: 2240 vs 2246 - 0.27% difference
⚠️ colmap_37: space 3D points: 2476 vs 2466 - 0.40% difference
⚠️ colmap_38: space 3D points: 2527 vs 2535 - 0.32% difference
⚠️ colmap_39: space 3D points: 2657 vs 2647 - 0.38% difference
⚠️ colmap_4: space 3D points: 2443 vs 2438 - 0.20% difference
⚠️ colmap_40: space 3D points: 2721 vs 2724 - 0.11% difference
⚠️ colmap_41: space 3D points: 2868 vs 2890 - 0.77% difference
⚠️ colmap_42: space 3D points: 2949 vs 2957 - 0.27% difference
⚠️ colmap_43: space 3D points: 3084 vs 3081 - 0.10% difference
⚠️ colmap_44: space 3D points: 3152 vs 3151 - 0.03% difference
⚠️ colmap_45: space 3D points: 3137 vs 3154 - 0.54% difference
⚠️ colmap_46: space 3D points: 3175 vs 3192 - 0.54% difference
⚠️ colmap_47: space 3D points: 3154 vs 3155 - 0.03% difference
⚠️ colmap_48: space 3D points: 3130 vs 3122 - 0.26% difference
⚠️ colmap_49: space 3D points: 3000 vs 3016 - 0.53% difference
⚠️ colmap_5: space 3D points: 2538 vs 2535 - 0.12% difference
⚠️ colmap_6: space 3D points: 2630 vs 2633 - 0.11% difference
⚠️ colmap_7: space 3D points: 2694 vs 2681 - 0.48% difference
⚠️ colmap_8: space 3D points: 2795 vs 2798 - 0.11% difference
⚠️ colmap_9: space 3D points: 2867 vs 2872 - 0.17% difference
Checking /home/remmel/workspace/dataset/immersive/before/02_Flames_undist/colmap_* with after
⚠️ colmap_0: space 3D points: 3201 vs 3210 - 0.28% difference
⚠️ colmap_1: space 3D points: 3296 vs 3281 - 0.46% difference
⚠️ colmap_10: space 3D points: 4953 vs 4974 - 0.42% difference
⚠️ colmap_11: space 3D points: 4946 vs 4933 - 0.26% difference
⚠️ colmap_12: space 3D points: 5052 vs 5056 - 0.08% difference
⚠️ colmap_13: space 3D points: 4845 vs 4836 - 0.19% difference
⚠️ colmap_14: space 3D points: 4493 vs 4478 - 0.33% difference
⚠️ colmap_16: space 3D points: 4391 vs 4387 - 0.09% difference
⚠️ colmap_17: space 3D points: 4450 vs 4462 - 0.27% difference
⚠️ colmap_18: space 3D points: 4436 vs 4445 - 0.20% difference
⚠️ colmap_19: space 3D points: 4435 vs 4434 - 0.02% difference
⚠️ colmap_2: space 3D points: 3605 vs 3607 - 0.06% difference
⚠️ colmap_20: space 3D points: 4180 vs 4178 - 0.05% difference
⚠️ colmap_21: space 3D points: 4273 vs 4285 - 0.28% difference
⚠️ colmap_22: space 3D points: 4375 vs 4356 - 0.43% difference
⚠️ colmap_23: space 3D points: 4492 vs 4503 - 0.24% difference
⚠️ colmap_24: space 3D points: 4487 vs 4499 - 0.27% difference
⚠️ colmap_25: space 3D points: 4365 vs 4371 - 0.14% difference
⚠️ colmap_26: space 3D points: 4342 vs 4349 - 0.16% difference
⚠️ colmap_27: space 3D points: 4480 vs 4450 - 0.67% difference
⚠️ colmap_28: space 3D points: 4426 vs 4427 - 0.02% difference
⚠️ colmap_29: space 3D points: 4279 vs 4309 - 0.70% difference
⚠️ colmap_3: space 3D points: 3724 vs 3725 - 0.03% difference
⚠️ colmap_30: space 3D points: 4132 vs 4129 - 0.07% difference
⚠️ colmap_31: space 3D points: 4296 vs 4293 - 0.07% difference
⚠️ colmap_32: space 3D points: 4244 vs 4247 - 0.07% difference
⚠️ colmap_33: space 3D points: 4034 vs 4041 - 0.17% difference
⚠️ colmap_34: space 3D points: 3665 vs 3686 - 0.57% difference
⚠️ colmap_35: space 3D points: 3536 vs 3553 - 0.48% difference
⚠️ colmap_36: space 3D points: 3550 vs 3556 - 0.17% difference
⚠️ colmap_37: space 3D points: 4071 vs 4072 - 0.02% difference
⚠️ colmap_38: space 3D points: 4215 vs 4248 - 0.78% difference
⚠️ colmap_39: space 3D points: 4340 vs 4348 - 0.18% difference
⚠️ colmap_4: space 3D points: 4114 vs 4138 - 0.58% difference
⚠️ colmap_40: space 3D points: 4507 vs 4532 - 0.55% difference
⚠️ colmap_41: space 3D points: 4789 vs 4760 - 0.61% difference
⚠️ colmap_42: space 3D points: 4839 vs 4864 - 0.52% difference
⚠️ colmap_43: space 3D points: 5040 vs 5049 - 0.18% difference
⚠️ colmap_44: space 3D points: 5093 vs 5094 - 0.02% difference
⚠️ colmap_45: space 3D points: 5144 vs 5162 - 0.35% difference
⚠️ colmap_46: space 3D points: 5231 vs 5217 - 0.27% difference
⚠️ colmap_47: space 3D points: 5113 vs 5110 - 0.06% difference
⚠️ colmap_48: space 3D points: 5073 vs 5084 - 0.22% difference
⚠️ colmap_49: space 3D points: 4878 vs 4894 - 0.33% difference
⚠️ colmap_5: space 3D points: 4225 vs 4234 - 0.21% difference
⚠️ colmap_6: space 3D points: 4399 vs 4412 - 0.30% difference
⚠️ colmap_7: space 3D points: 4542 vs 4521 - 0.46% difference
⚠️ colmap_8: space 3D points: 4672 vs 4677 - 0.11% difference
⚠️ colmap_9: space 3D points: 4828 vs 4827 - 0.02% difference

Process finished with exit code 0
```

</details>

**Comment by lizhan17** [comment]
Thank you !

**Pull request merged**
